version: 0.0
os: linux
files:
  - source: /
    destination: /deploy
hooks:
  BeforeInstall:
    - location: deploy/install.sh
      timeout: 300
      runas: root
    - location: deploy/server_start.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: deploy/server_stop.sh
      timeout: 60
      runas: root
